source 'https://github.com/cheng-ren/RCSpecs.git'

use_frameworks!

platform :ios, '10.0'

target 'BizComponentA_Example' do
  pod 'BizComponentA', :path => '../'

  target 'BizComponentA_Tests' do
    inherit! :search_paths

    
  end
end
